const grid=document.getElementById("grid"),stateEl=document.getElementById("state");let localStream=null,roomId=new URLSearchParams(location.search).get("room")||"general",meetingId=null,channel=null,peers=new Map(),user=null;
function toast(x){const t=document.getElementById("toast");t.textContent=x;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2200)}
function tile(id,label,stream,muted=false){let old=document.getElementById("v-"+id);if(!old){old=document.createElement("div");old.className="tile";old.id="v-"+id;old.innerHTML=`<video autoplay playsinline ${muted?"muted":""}></video><span>${label}</span>`;grid.appendChild(old)}old.querySelector("video").srcObject=stream}
async function signal(to,type,payload){if(!RT.client||!meetingId)return;await RT.client.from("meeting_signals").insert({meeting_id:meetingId,sender_id:user.id,recipient_id:to,signal_type:type,payload})}
async function createPeer(peerId,initiator){let pc=peers.get(peerId);if(pc)return pc;pc=new RTCPeerConnection({iceServers:window.HUB_ICE_SERVERS||[]});peers.set(peerId,pc);localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.onicecandidate=e=>{if(e.candidate)signal(peerId,"ice",e.candidate)};pc.ontrack=e=>tile(peerId,"Member",e.streams[0]);pc.onconnectionstatechange=()=>{if(["failed","closed","disconnected"].includes(pc.connectionState)){pc.close();peers.delete(peerId);document.getElementById("v-"+peerId)?.remove()}};if(initiator){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await signal(peerId,"offer",offer)}return pc}
async function handleSignal(s){if(s.sender_id===user.id)return;let pc=peers.get(s.sender_id);if(s.signal_type==="offer"){pc=await createPeer(s.sender_id,false);await pc.setRemoteDescription(s.payload);const ans=await pc.createAnswer();await pc.setLocalDescription(ans);await signal(s.sender_id,"answer",ans)}else if(s.signal_type==="answer"&&pc){await pc.setRemoteDescription(s.payload)}else if(s.signal_type==="ice"&&pc){try{await pc.addIceCandidate(s.payload)}catch(e){}}}
async function start(){
 user=await auth();if(!RT.client||!user){stateEl.textContent="Sign in and configure Supabase to start a live meeting";return}
 localStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});tile(user.id,"You",localStream,true);
 const {data:meeting}=await RT.client.from("meetings").select("id").eq("room_key",roomId).eq("status","live").maybeSingle();
 if(meeting)meetingId=meeting.id;else{const {data,error}=await RT.client.from("meetings").insert({title:"Development Team Meeting",host_id:user.id,status:"live",room_key:roomId}).select("id").single();if(error){stateEl.textContent=error.message;return}meetingId=data.id}
 await RT.client.from("meeting_participants").upsert({meeting_id:meetingId,user_id:user.id});
 channel=RT.client.channel("meeting:"+meetingId).on("postgres_changes",{event:"INSERT",schema:"public",table:"meeting_signals",filter:"meeting_id=eq."+meetingId},p=>handleSignal(p.new)).on("postgres_changes",{event:"INSERT",schema:"public",table:"meeting_participants",filter:"meeting_id=eq."+meetingId},async p=>{if(p.new.user_id!==user.id)await createPeer(p.new.user_id,true)}).subscribe();
 const {data:people}=await RT.client.from("meeting_participants").select("user_id").eq("meeting_id",meetingId).is("left_at",null);for(const p of people||[])if(p.user_id!==user.id)await createPeer(p.user_id,true);
 stateEl.textContent="Live · encrypted WebRTC media";
}
document.getElementById("mic").onclick=()=>localStream?.getAudioTracks().forEach(t=>t.enabled=!t.enabled);
document.getElementById("cam").onclick=()=>localStream?.getVideoTracks().forEach(t=>t.enabled=!t.enabled);
document.getElementById("share").onclick=async()=>{try{const s=await navigator.mediaDevices.getDisplayMedia({video:true});const track=s.getVideoTracks()[0];for(const pc of peers.values()){const sender=pc.getSenders().find(x=>x.track?.kind==="video");if(sender)await sender.replaceTrack(track)}tile(user.id,"You",s,true);track.onended=()=>localStream&&document.getElementById("v-"+user.id).querySelector("video").srcObject=localStream}catch(e){}};
document.getElementById("invite").onclick=async()=>{await navigator.clipboard?.writeText(location.href);toast("Meeting link copied")};
document.getElementById("leave").onclick=async()=>{for(const pc of peers.values())pc.close();localStream?.getTracks().forEach(t=>t.stop());if(RT.client&&meetingId&&user)await RT.client.from("meeting_participants").update({left_at:new Date().toISOString()}).eq("meeting_id",meetingId).eq("user_id",user.id);location.href="chat.html"};
start();
